// src/constants/services.ts
export const SERVICES = [
    {
      serviceName: 'Hair Styling',
      pricing: 39.99,
      description: 'Professional hair styling services for all occasions.',
      createdAt: '2025-07-01T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?hair,salon'],
      deliveryTime: '2 days',
      citiesCovered: ['Casablanca', 'Rabat', 'Marrakech'],
    },
    {
      serviceName: 'Facial Treatment',
      pricing: 49.99,
      description: 'Relaxing and rejuvenating facial care by experts.',
      createdAt: '2025-06-28T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?facial,beauty'],
      deliveryTime: '1 day',
      citiesCovered: ['Tangier', 'Agadir', 'Fes'],
    },
    {
      serviceName: 'House Cleaning',
      pricing: 29.99,
      description: 'Deep home cleaning service using eco-friendly products.',
      createdAt: '2025-06-25T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?cleaning,home'],
      deliveryTime: '1 day',
      citiesCovered: ['Casablanca', 'Fes', 'Kenitra'],
    },
    {
      serviceName: 'Electric Repair',
      pricing: 59.99,
      description: 'Licensed electrician available for home or office repairs.',
      createdAt: '2025-06-20T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?electrician,tools'],
      deliveryTime: '3 days',
      citiesCovered: ['Meknes', 'Oujda', 'Tetouan'],
    },
    {
      serviceName: 'Carpet Cleaning',
      pricing: 44.99,
      description: 'Steam carpet cleaning with premium machines.',
      createdAt: '2025-06-18T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?carpet,cleaning'],
      deliveryTime: '2 days',
      citiesCovered: ['Casablanca', 'Mohammedia'],
    },
    {
      serviceName: 'Home Tutoring',
      pricing: 99.99,
      description: 'One-on-one tutoring for school and university students.',
      createdAt: '2025-07-02T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?tutor,student'],
      deliveryTime: '1 day',
      citiesCovered: ['Rabat', 'El Jadida'],
    },
    {
      serviceName: 'Plumbing Services',
      pricing: 89.99,
      description: 'Emergency plumbing service with guaranteed results.',
      createdAt: '2025-06-29T00:00:00Z',
      serviceImgs: ['https://source.unsplash.com/featured/?plumber,tools'],
      deliveryTime: 'Same day',
      citiesCovered: ['Agadir', 'Safi'],
    },
  ];
  