// src/constants/mockUsers.ts
export const USERS = [
    {
      id: 1,
      name: 'Ali Bouzid',
      age: 34,
      city: 'Casablanca',
      job: 'Electrician',
      rating: 4.8,
      views: 234,
      phoneViews: 24,
      description: 'Expert in residential and commercial electrical systems.',
      imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
      id: 2,
      name: 'Meryem El Fassi',
      age: 28,
      city: 'Rabat',
      job: 'Plumber',
      rating: 4.5,
      views: 187,
      phoneViews: 34,
      description: 'Certified plumber with fast and reliable service.',
      imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
    {
      id: 3,
      name: 'Omar Chafai',
      age: 30,
      city: 'Fes',
      job: 'Carpenter',
      rating: 4.2,
      views: 142,
      phoneViews: 18,
      description: 'Specialized in custom furniture and wood restoration.',
      imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
      id: 4,
      name: 'Sara Amrani',
      age: 32,
      city: 'Agadir',
      job: 'Housekeeper',
      rating: 4.9,
      views: 268,
      phoneViews: 40,
      description: 'Detail-oriented home cleaning with natural products.',
      imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
    },
    {
      id: 5,
      name: 'Hamza Outaleb',
      age: 29,
      city: 'Marrakech',
      job: 'Gardener',
      rating: 4.1,
      views: 133,
      phoneViews: 20,
      description: 'Landscape design and maintenance for urban homes.',
      imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
      id: 6,
      name: 'Imane Bakkali',
      age: 26,
      city: 'Tangier',
      job: 'Tutor',
      rating: 5.0,
      views: 312,
      phoneViews: 50,
      description: 'Experienced tutor for high school math and science.',
      imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
    {
      id: 7,
      name: 'Youssef Hammani',
      age: 38,
      city: 'Meknes',
      job: 'Mechanic',
      rating: 4.3,
      views: 156,
      phoneViews: 19,
      description: 'Car diagnostics and repairs with genuine parts.',
      imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
      id: 8,
      name: 'Nawal Idrissi',
      age: 31,
      city: 'El Jadida',
      job: 'Hair Stylist',
      rating: 4.7,
      views: 214,
      phoneViews: 28,
      description: 'Trendy cuts and styles for all hair types.',
      imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
      id: 9,
      name: 'Rachid Kabbaj',
      age: 36,
      city: 'Safi',
      job: 'Painter',
      rating: 4.4,
      views: 189,
      phoneViews: 21,
      description: 'Interior and exterior painting for homes and offices.',
      imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
      id: 10,
      name: 'Lina Benchekroun',
      age: 27,
      city: 'Oujda',
      job: 'Facialist',
      rating: 4.6,
      views: 198,
      phoneViews: 33,
      description: 'Facials and skincare therapy with natural ingredients.',
      imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
  ];
  